version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.44
    networks:
      - jaeger-example
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  py-service:
    build: apps/py
    ports:
      - "8080:8080"
    environment: 
      - NODEJS_SERVICE_URL=nodejs-service:3000
    networks:
      - jaeger-example

  nodejs-service:
    build: apps/nodejs
    ports:
      - "3000:3000"
    environment: 
      - PY_SERVICE_URL=py-service:8080
    networks:
      - jaeger-example

networks:
  jaeger-example: